name: ${__PROJECT_NAME}

services:
  mariadb:
    image: ${__MARIADB_IMAGE}
    container_name: ${__MARIADB_CONTAINER}
    pull_policy: never
    healthcheck: &health_authority
      test: ["CMD-SHELL", "test -f $__HEALTH || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
    build: ${__MARIADB_CONTEXT}
    expose:
      - ${__MARIADB_PORT}
    env_file: ./.env
    volumes:
      - mariadb:${__DATABASE_DIR}
    networks:
      - ${__NETWORK_NAME}
    secrets:
      - db_password
      - db_root_password
    restart: on-failure

  wordpress:
    image: ${__WORDPRESS_IMAGE}
    container_name: ${__WORDPRESS_CONTAINER}
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    pull_policy: never
    healthcheck: *health_authority
    build: ${__WORDPRESS_CONTEXT}
    expose:
      - ${__WORDPRESS_PORT}
    env_file: ./.env
    volumes:
      - wordpress:${__WORDPRESS_DIR}
    networks:
      - ${__NETWORK_NAME}
    secrets:
      - wp_admin_password
      - wp_user2_password
      - wp_credentials
      - db_password
    restart: on-failure
  
  nginx:
    image: ${__NGINX_IMAGE}
    container_name: ${__NGINX_CONTAINER}
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
    pull_policy: never
    build: ${__NGINX_CONTEXT}
    env_file: ./.env
    volumes:
      - wordpress:${__WORDPRESS_DIR}
    networks:
      - ${__NETWORK_NAME}
    ports:
      - ${__HOST_PORT}:${__NGINX_PORT}
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${__WORDPRESS_FL_VOLUME}
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${__WORDPRESS_DB_VOLUME}

networks:
  inception:
    driver: bridge

secrets:
  wp_credentials:
    file: ../secrets/wp_credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user2_password:
    file: ../secrets/wp_user2_password.txt