name: ${__PROJECT_NAME}

services:
  mariadb:
    image: ${__MARIADB_IMAGE}
    container_name: ${__MARIADB_CONTAINER}
    pull_policy: never
    build: ${__MARIADB_CONTEXT}
    expose:
      - ${__MARIADB_PORT}
    env_file: ./.env
    volumes:
      - mariadb:${__DATABASE_DIR}
    networks:
      - ${__NETWORK_NAME}
    # restart: on-failure

  wordpress:
    image: ${__WORDPRESS_IMAGE}
    container_name: ${__WORDPRESS_CONTAINER}
    depends_on:
      - mariadb
    pull_policy: never
    build: ${__WORDPRESS_CONTEXT}
    expose:
      - ${__WORDPRESS_PORT}
    env_file: ./.env
    volumes:
      - wordpress:${__WORDPRESS_DIR}
    networks:
      - ${__NETWORK_NAME}
    # restart: on-failure
  
  nginx:
    image: ${__NGINX_IMAGE}
    container_name: ${__NGINX_CONTAINER}
    depends_on:
      - wordpress
    pull_policy: never
    build: ${__NGINX_CONTEXT}
    env_file: ./.env
    volumes:
      - wordpress:${__WORDPRESS_DIR}
    networks:
      - ${__NETWORK_NAME}
    ports:
      - ${__HOST_PORT}:${__NGINX_PORT}
    # restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${__WORDPRESS_FL_VOLUME}
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${__WORDPRESS_DB_VOLUME}

networks:
  inception:
    driver: bridge